### ISSUE TITLE
Missing releases

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [bokeh/jupyter_bokeh#104]
The readme file states what versions are compatible with what versions of JupyterLab. Unfortunately, there is no release to download for the old versions. As there are also no tags for those old versions, I now have to go through commits and try to find the correct commit for a version and somehow download that as one file, if possible.

**Comment by mattpap** [comment]
Those releases are effectively lost (not available from anaconda.org and pypi). We don't maintain releases on GitHub They appear there just as a side effect of tagging commits. Do you have a use case where you need to support JLab < 1.0?

**Comment by ZelphirKaltstahl** [comment]
Yes, currently I need to support `0.35.6` in 2 places, although both are planned to migrate to `2.x.y`.

I now chose to take the archive from the repo as follows:

``` shell
#!/usr/bin/env bash

set -Eeuxo pipefail

JUPYTERLAB_BOKEH_VERSION="2.0.1"
JUPYTERLAB_BOKEH_COMMIT_HASH="293b56eb54ccc90e963f672be05c4665a5287965"
JUPYTERLAB_BOKEH_DL_URL="https://github.com/bokeh/jupyter_bokeh/archive/${JUPYTERLAB_BOKEH_COMMIT_HASH}.zip"
JUPYTERLAB_BOKEH_ARCHIVE_FILENAME="jupyter-bokeh-${JUPYTERLAB_BOKEH_VERSION}.zip"
JUPYTERLAB_BOKEH_SHA512SUM="205cf6740ef4f4e65905216b3b4a797f7989429d3f83b1df7596df163f6afe1d71018958886ae32dfedf0d586ffe9c488942624d86e295e15ea2bca3f20e9445"

wget \
    --output-document="${JUPYTERLAB_BOKEH_ARCHIVE_FILENAME}" \
    "${JUPYTERLAB_BOKEH_DL_URL}" \
    && echo "${JUPYTERLAB_BOKEH_SHA512SUM} ${JUPYTERLAB_BOKEH_ARCHIVE_FILENAME}" | sha512sum -c - \
    && unzip -n "${JUPYTERLAB_BOKEH_ARCHIVE_FILENAME}"
```

**Comment by bryevdv** [comment]
single affected user has WAR, and there is nothing we can do in any case so I am closing this.
