### ISSUE TITLE
Jupyterlab hanging with [LabBuildApp] WARNING | The extension "jupyterlab_bokeh" is outdated.

### ISSUE THREAD

**Issue by Ben-Epstein** [bokeh/jupyter_bokeh#109]
I'm trying to build a docker image for jupyterlab but every time I try to install any extensions I get the warning 
`[LabBuildApp] WARNING | The extension "jupyterlab_bokeh" is outdated.` and this causes the build to stall out.

I'm trying to upgrade it but nothing seems to work
```
RUN conda install nodejs && \
    pip install --upgrade jupyterlab==2.0.0 jupyter_bokeh==2.0.0 && \
    jupyter labextension install --no-build @jupyter-widgets/jupyterlab-manager && \
    jupyter labextension install --no-build @bokeh/jupyter_bokeh@2.0.0 && \
    jupyter labextension update --all && \
    jupyter labextension install --no-build beakerx-jupyterlab && \
    jupyter labextension install --no-build jupyterlab_sparkmonitor-s && \
    jupyter lab build --dev-build=False --minimize=False
``` 
Throws the output
```
No compatible version found for jupyterlab_bokeh!
Updating @bokeh/jupyter_bokeh to version 2.0.3
Extension '@jupyter-widgets/jupyterlab-manager' already up to date
Building jupyterlab assets (build:prod:minimize)
The extension "jupyterlab_bokeh" is outdated.
```

How can I fix this warning/upgrade jupyterlab_bokeh?

Thanks!

**Comment by bryevdv** [comment]
Running the commands individually in a clean conda env with just python and nodejs, I can't repro any warning on OSX. cc @philippjfr @mattpap ?

**Comment by Ben-Epstein** [comment]
@bryevdv What i'm noticing which is odd is that it's not referencing `@bokeh/jupyter_bokeh` it's referencing `jupyterlab_bokeh`

I'm going to try:
`jupyter labextension uninstall jupyterlab_bokeh` because that seems different. Do you know why it's referenced like that?

**Comment by bryevdv** [comment]
The warning is almost certainly due to the fact that jupyterlab_bokeh is deprecated:

https://www.npmjs.com/package/jupyterlab_bokeh

But I don't know why you are getting it in the first place. Just following just the steps above I don't get the jupyterlab_bokeh extension installed:
```
(jlabtesst) ❯ jupyter labextension list
JupyterLab v2.0.0
Known labextensions:
   app dir: /Users/bryan/anaconda/share/jupyter/lab
        @bokeh/jupyter_bokeh v2.0.3  enabled  OK
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        beakerx-jupyterlab v1.4.1  enabled  OK
        jupyterlab_sparkmonitor-s v1.1.0  enabled  OK
```

**Comment by Ben-Epstein** [comment]
@bryevdv It doesn't seem to exist before running `pip install --upgrade jupyterlab==2.0.0 jupyter_bokeh==2.0.0` but I added `jupyter labextension uninstall jupyterlab_bokeh` after that which solved the problem. I'm definitely confused but I'll close the issue for now, thanks!
