### ISSUE TITLE
what does this plugin do?

### ISSUE THREAD

**Issue by bobcolner** [bokeh/jupyter_bokeh#113]
zero description of the functionality provided in the readme...

**Comment by bryevdv** [comment]
@bobcolner I am not sure what you are expected, the README states:

> A Jupyter extension for rendering Bokeh content within Jupyter. 

Which is exactly what this plugin is/does.

**Comment by bryevdv** [comment]
If your question is really "What is Bokeh?" then I've added link to https://bokeh.org from that first sentence.
