### ISSUE TITLE
Any plans to add support for jupyterlab 3.0 ?

### ISSUE THREAD

**Issue by gshklover** [bokeh/jupyter_bokeh#116]

**Comment by bryevdv** [comment]
@gshklover Was not aware it was coming. Please open an issue about jupyterlab 3.0 in the main repo.

**Comment by gshklover** [comment]
Probably already covered by this issue: https://github.com/bokeh/bokeh/issues/10569

**Comment by bryevdv** [comment]
Closing in favor of the issue in the main repo
