### ISSUE TITLE
Decide on distro channels

### ISSUE THREAD

**Issue by bryevdv** [bokeh/jupyter_bokeh#125]
Specifically: Do we support NPM / manual installation in addition to pre-built pip/conda packages? It's unclear that the current 3.0 NPM package works. I am personally OK with only having the pre-built packages as options as it is less for us to worry about. 

If we do want to support NPM install for this extension then the build or other issues with it need to be sorted out. 

cc @bokeh/dev

**Comment by mattpap** [comment]
If jlab doesn't require a npm package, then we should not maintain it, especially given it wouldn't be of any use on its own.

**Comment by bryevdv** [comment]
It's not *required* but it is *possible* to offer one for installation using `jupyter labextension` directly. I just don't see why that would be valuable enough to bother doing though.

**Comment by bryevdv** [comment]
Unless @philippjfr has any objection I think should just proceed with pip/conda only going forward. I'll close this issue EOD today unless there is further comment.

**Comment by philippjfr** [comment]
I'm a strong +1 on offering pip/conda only. If we already published 3.0 to npm I think we should pull it since it doesn't seem to work anyway.

**Comment by bryevdv** [comment]
👍 I will close this now then

**Comment by bryevdv** [comment]
I deprecated all the 3.0.0 versions (including dev) with the message
> Use pre-built pip or conda packages instead
