### ISSUE TITLE
Conda package for 3.0 version

### ISSUE THREAD

**Issue by bryevdv** [bokeh/jupyter_bokeh#126]
3.0 version released with only pip package in order to get something in to the hands of users faster. Need to figure out and document steps for conda release and release. 

Do conda pkgs for this go on a channel on anaconda.org? conda-forge? 

related: #75

**Comment by philippjfr** [comment]
They are already published to the bokeh channel: https://anaconda.org/bokeh/jupyter_bokeh

I can also work on createing a conda-forge recipe and petition to get it on conda defaults.

**Comment by philippjfr** [comment]
Staged conda-forge feedstock here: https://github.com/conda-forge/staged-recipes/pull/14345

**Comment by philippjfr** [comment]
Turns out there already is a conda-forge feedstock and I've asked to be added here: https://github.com/conda-forge/jupyter_bokeh-feedstock/issues/3
