### ISSUE TITLE
Error: Module @bokeh/jupyter_bokeh, semver range ^3.0.2 is not registered as a widget module

### ISSUE THREAD

**Issue by MarcSkovMadsen** [bokeh/jupyter_bokeh#134]
jupyter-bokeh: 3.0.2
jupyterlab: 3.0.16
panel: 0.11.3

I am trying to get Panel working inside VS Code (code-server) on a Jupyter Hub. But I get the error

```bash
Error: Module @bokeh/jupyter_bokeh, semver range ^3.0.2 is not registered as a widget module
```

It's related to this issue. Where I could get it working when starting from a fresh environment https://github.com/bokeh/jupyter_bokeh/issues/131

![image](https://user-images.githubusercontent.com/42288570/122233906-b7ef0300-cebc-11eb-84b8-7a7f385fde43.png)

The problem here is that I am not in control of the `base` environment which all users of the jupyter hub are using.

**Comment by MarcSkovMadsen** [comment]
I tried creating a fresh conda environment `panelvs` via `conda create -n panelvs -c conda-forge panel jupyter_bokeh param`

But the problem persists

![image](https://user-images.githubusercontent.com/42288570/122236135-8ecf7200-cebe-11eb-9178-7e489f3aa163.png)

**Comment by bryevdv** [comment]
This seems to be an error message that has [plagued many different projects](https://www.google.com/search?q=%22is+not+registered+as+a+widget+module%22&client=safari&rls=en&sxsrf=ALeKk028cz7DEDelTMaNRXYaqTr-rqsEwg%3A1623862355513&ei=UyzKYNrkHpT_-wS7pZ74BA&oq=%22is+not+registered+as+a+widget+module%22&gs_lcp=Cgdnd3Mtd2l6EAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsANQAFgAYIpZaAFwAngAgAE_iAE_kgEBMZgBAKoBB2d3cy13aXrIAQbAAQE&sclient=gws-wiz&ved=0ahUKEwia2vTWzpzxAhWU_54KHbuSB08Q4dUDCA0&uact=5). From a glance it always seems to come down to some dependency change. The NPM module is the same as it was before, so what else has changed? Have you compared jupyter-lab and other package versions to what was working before?

**Comment by coryjmaklin** [comment]
Did you find a resolution? Widgets do not work for me, and I'm seeing a similar message. 
Error: Module @bokeh/jupyter_bokeh, semver range ^3.0.4 is not registered as a widget module
Versions:
jupyterlab                    3.1.12
bokeh                         2.3.3
jupyter-bokeh                 3.0.4

**Comment by MarcSkovMadsen** [comment]
I've not had the problem for a while. As far as I remember the problem was solved in the bokeh end ??

**Comment by bryevdv** [comment]
Closing this as stale since it has not been reproducible, and everything I can find online for other projects about it seems to pointing ultimately to some version incompatibilities in the environment.
