### ISSUE TITLE
interactive plots in jupyterlab 

### ISSUE THREAD

**Issue by jamestwebber** [bokeh/jupyter_bokeh#135]
(apologies if there's a better venue for this type of question!)

I use jupyter lab for notebooks and I am exploring using bokeh for interactive plotting but had trouble getting it to work. It seems to work in a classic notebook, but something goes wrong in jupyterlab. e.g. [this example](http://holoviews.org/reference/streams/bokeh/Selection1D_points.html) works fine in the classic notebook, but in lab the selection event doesn't seem to do anything (nothing shows up in the second plot).

Similarly I can use [this example from SO](https://stackoverflow.com/a/56756358) in a classic notebook but the `selection` value is not updated in a lab notebook.

I have `JupyterLab v3.0.16` and `@bokeh/jupyter_bokeh v3.0.2` installed. I installed in a fresh environment on OS X so things should be pretty up to date.

If there's a better place to ask these kinds of questions, happy to go there instead! Thanks

**Comment by bryevdv** [comment]
@jamestwebber All of the examples you link to are Holoviews code. Holoviews is a separate project and maintained by a different organization. I would suggest starting with an issue in the [holoviews issue tracker](https://github.com/holoviz/holoviews/issues) or else a support topic in the [holoviz Discourse](https://discourse.holoviz.org). If the holoviz issue determines there is an issue with the actual Bokeh Jupyter extension, they will file an issue here with relevant details. 

cc @philippjfr
