### ISSUE TITLE
Cant install 3.0.4 on windows 11 and Python 3.9.7+

### ISSUE THREAD

**Issue by ItamarShDev** [bokeh/jupyter_bokeh#146]
trying to build our JLab env in Windows 11 failed with the following error:

```log 
Failed to build jupyter-bokeh
ERROR: Could not build wheels for jupyter-bokeh which use PEP 517 and cannot be installed directly
WARNING: You are using pip version 21.1.2; however, version 22.0.3 is available.
You should consider upgrading via the 'C:\Users\ItamarSharify\Documents\modeling\MOD\Scripts\python.exe -m pip install --upgrade pip' command.
```

The same error happened on:
1. both old and latest pip
2. both old and latest setuptools
3. python 3.9.7 and python 3.9.9
4. 2 different windows PCs, one with Windows 11 and one with Windows 10

This is not happening in Ubuntu 20.04 machines.
We have one Windows 11 pc that for some reason manages to install it.

Reverting to 3.0.2 works.

Here is the full pp install log:
[pip install.txt](https://github.com/bokeh/jupyter_bokeh/files/8167760/pip.install.txt)

**Comment by bryevdv** [comment]
No idea what might be going on, but you might try the suggestions here in the  mean time:

https://stackoverflow.com/a/63999596/3406693

**Comment by bryevdv** [comment]
@philippjfr @mattpap do we not publish wheels? Is that intentional? I thought we did now but I only see sdist at https://pypi.org/project/jupyter-bokeh/#files

**Comment by bryevdv** [comment]
@ItamarShDev there is now a wheel (just for 3.0.4) 
```
dev-3.9 ❯ pip install jupyter_bokeh
Collecting jupyter_bokeh
  Downloading jupyter_bokeh-3.0.4-py3-none-any.whl (1.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 12.8 MB/s eta 0:00:00
```
can you see if this now works for you? If so this issue can be closed since the other issue is still open about publishing wheels in general

**Comment by ItamarShDev** [comment]
Works! thank you very much @bryevdv !
![image](https://user-images.githubusercontent.com/953371/156645564-335b3c46-ff99-463f-8eb7-9f5e91b859a3.png)

**Comment by philippjfr** [comment]
Thanks @bryevdv! I've never actually had the time to get set up to build and upload any packages for this repo. At some point I would like to automate it with GH Actions like we have for HoloViz packages.

**Comment by ItamarShDev** [comment]
I would be happy to help if you could point me to the right direction :)

**Comment by jgbustos** [comment]
> trying to build our JLab env in Windows 11 failed with the following error:
> 
> ```
> Failed to build jupyter-bokeh
> ERROR: Could not build wheels for jupyter-bokeh which use PEP 517 and cannot be installed directly
> WARNING: You are using pip version 21.1.2; however, version 22.0.3 is available.
> You should consider upgrading via the 'C:\Users\ItamarSharify\Documents\modeling\MOD\Scripts\python.exe -m pip install --upgrade pip' command.
> ```
> 
> The same error happened on:
> 
>     1. both old and latest pip
> 
>     2. both old and latest setuptools
> 
>     3. python 3.9.7 and python 3.9.9
> 
>     4. 2 different windows PCs, one with Windows 11 and one with Windows 10
> 
> 
> This is not happening in Ubuntu 20.04 machines. We have one Windows 11 pc that for some reason manages to install it.
> 
> Reverting to 3.0.2 works.
> 
> Here is the full pp install log: [pip install.txt](https://github.com/bokeh/jupyter_bokeh/files/8167760/pip.install.txt)

I have exactly the same problem on my machine. The only way I can make it build is by forcing pip and setuptools into legacy behaviour, ignoring pyproject.toml and building based on setup.py.

Try running
`pip install  -U --use-deprecated=legacy-resolver jupyter-bokeh`

**Comment by pinusm** [comment]
Another solution, as pointed out by @jgbustos, is to allow Windows to use longer paths and removing the max path limitation.
> Your administrator will need to activate the “Enable Win32 long paths” group policy, or set LongPathsEnabled to 1 in the registry key HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem.
>...
> After changing the above option, no further configuration is required.

See source [here](https://docs.python.org/3/using/windows.html#removing-the-max-path-limitation).
