### ISSUE TITLE
Update `trigger_json_event` for Bokeh 3

### ISSUE THREAD

**Issue by Hoxbro** [bokeh/jupyter_bokeh#184]
`trigger_json_event` no longer exists in Bokeh 3.1. 

https://github.com/bokeh/jupyter_bokeh/blob/f343b904b2d6f95b62537abb6b0e763bafb617b3/jupyter_bokeh/widgets.py#L136

**Comment by mattpap** [comment]
I fixed this in PR #178, among other issues related to bokeh 3.
