### ISSUE TITLE
whould it be possible to have wheels again in the pypi download ?

### ISSUE THREAD

**Issue by stonebig** [bokeh/jupyter_bokeh#193]
last published wheel was jupyter_bokeh-3.0.4-py3-none-any.whl

**Comment by mattpap** [comment]
Sure. I uploaded a wheel for 3.0.7. I will update our build procedure to include wheels.

**Comment by mattpap** [comment]
Wheels are now published for jupyter-bokeh releases. For example for the latest 4.0 release:
https://files.pythonhosted.org/packages/87/d2/4c0da13e7387494c914c739180797539cc8f81e353684329e9eae287085f/jupyter_bokeh-4.0.0-py3-none-any.whl
