### ISSUE TITLE
Where is jupyter_bokeh 4.0.0?

### ISSUE THREAD

**Issue by pythonic2020** [bokeh/jupyter_bokeh#197]
It appears that about six months have gone by since anyone has made a PR that starts down the road of making the extension compatible with JupyterLab 4+. Have bokeh devs just given up on this effort? A [PR](https://github.com/bokeh/jupyter_bokeh/pull/196) for jupyter_bokeh 3.0.8 from last summer is a dead end.

**Comment by bryevdv** [comment]
The answer is the same answer that is always and forever the answer in open source: there is more work than people.

**Comment by pythonic2020** [comment]
Pinning conda environments as below solves any update-related issues with Jupyter, ensuring that all bokeh interactive functions work perfectly:

jupyterlab==3.6.6
notebook==6.5.6

**Comment by mattpap** [comment]
jupyter_bokeh 4.0 was finally published.

**Comment by pythonic2020** [comment]
Awesome! Many thanks to all involved.
