### ISSUE TITLE
Concerning browser warnings with JupyterLab 3.6.7 and jupyter_bokeh 3.0.7 

### ISSUE THREAD

**Issue by mcg1969** [bokeh/jupyter_bokeh#198]
Sorry for the screenshot, it's surprisingly difficult to copy and paste compact text from the browser inspector. These browser warnings appear when jupyterlab 3.6.7 and jupyter_bokeh 3.0.7 are installed from Anaconda's defaults.

From my own work on labextensions, I believe it is because the npm "caret" operators "^" in this case are not correct—or perhaps more precisely, the JupyterLab ecosystem doesn't properly encode that there are breaking boundaries between 3.x and 4.x versions into its nodejs metadata. So 4.x packages are being improperly pulled into the build. The solution is to use ~ operators for all JupyterLab packages that the build depends on.

I'm not certain how dangerous these warnings are in this particular case.

<img width="914" alt="Screenshot 2024-02-28 at 6 18 45 PM" src="https://github.com/bokeh/jupyter_bokeh/assets/2797735/c508cb55-0742-42a0-b244-9bc8993f4c73">

**Comment by mattpap** [comment]
This happens because jupyter_bokeh 4.0 was published to fix this issue, but publishing to conda-forge was delayed.

**Comment by mattpap** [comment]
This should be resolved now that jupyter_bokeh 4.0 is published on conda-forge.

**Comment by mcg1969** [comment]
Alas the conda-forge build is not compatible with jlab 4.0.x in my experience; it seems to require 4.1
