### ISSUE TITLE
`push_notebook` not updating all views

### ISSUE THREAD

**Issue by fcollonval** [bokeh/jupyter_bokeh#45]
Duplicating output view in JupyterLab somehow breaks `push_notebook` as only one view gets updated (see gif for better demonstration).

![push_notebook](https://user-images.githubusercontent.com/8435071/42864894-4c6f308c-8a68-11e8-8341-06d68b974b3b.gif)

As our user story is about having the plot in parallel with the executed notebook, a workaround was implemented by using the sidecar widget (and adding to it an `anchor` attribute). See https://github.com/jupyter-widgets/jupyterlab-sidecar/pull/8

But as suggested by @jasongrout, `push_notebook` should be fixed. 

Versions used:
- bokeh 0.12.16
- jupyterlab 0.32.1
- jupyterlab_bokeh 0.5.0

Thanks for your awesome work

**Comment by bryevdv** [comment]
AFAIK this all working with versions >= 3.0 (currently pip installable)
