### ISSUE TITLE
AutocompleteInput dropdown is hidden

### ISSUE THREAD

**Issue by letalvoj** [bokeh/jupyter_bokeh#68]
I've just tried to use the `AutocompleteInput` and it's output both in jupyterlab and jupyter is hidden

<img width="1116" alt="Screenshot 2019-08-09 at 15 44 26" src="https://user-images.githubusercontent.com/5262321/62783483-d748c800-babc-11e9-8c82-b12a65630f75.png">

I tried to hack myself out of the issue by changing the CSS yet I can not force the appropriate `div` to `z-index` itself on top of the output. The value specified by bokeh is `100`. JupyterLab uses internally values up to `10001`. Moreover I am not sure whether I understand how exactly `z-index` should behave.

~Fortunately you can scroll trough the bk `div`, yet it is not really user friendly.~

jupyterlab v0.35.6
jupyterlab_bokeh v0.6.3

**Comment by letalvoj** [comment]
It it seems to be the same issue as with https://github.com/bokeh/jupyterlab_bokeh/issues/64. Yet IMO it is definitely issue with the integration, bokeh is fine.

The issue is with the `z-index` being ignored due to some reason with `position` or `overflow` settings of the parent divs. Anyway I found a way way to kind-of overcome this issue.

```
txt_input = AutocompleteInput(completions=['val1', 'val2'], callback=callback)
display(HTML('<style> .bk-root[id] { min-height:100pt } </style>'))
show(txt_input)
```

<img width="327" alt="Screenshot 2019-08-09 at 18 09 10" src="https://user-images.githubusercontent.com/5262321/62793001-cd30c480-bad0-11e9-9332-c3dd5c09fd2f.png">

**Comment by gmanolia** [comment]
Walkaround fix:

```
from IPython.core.display import display, HTML
txt_input = AutocompleteInput(completions=['val1', 'val2'], callback=callback)
display(HTML('<style> .bk-root[id] { min-height:100pt } </style>'))
show(txt_input)
```

Same as above, but I added the missing imports.

**Comment by bryevdv** [comment]
This needs to be validated w/ Jlab >= 3.0 and the 3.x extensions, or closed. @letalvoj can you provide an actual reproducer that we can investigate (i.e. actual code, not an image of code)?

**Comment by bryevdv** [comment]
Actually given this is Bokeh 1.x and there is no reproducer I'm going to close as stale. Anyone should feel free to open a new issue *with a reproducer* if there is indeed still any issue.
