### ISSUE TITLE
Rename to jupyter_bokeh

### ISSUE THREAD

**Issue by mattpap** [bokeh/jupyter_bokeh#72]
In light of PR #71, which makes this a dual jlab/nb extension, it would be nice to rename this repository to `jupyter_bokeh` and publish pip/conda/npm packages under that name. Currently references to `jupyterlab_bokeh` are pretty sparse. For example in bokeh we have:
```sh
$ git grep -l jupyterlab_bokeh
bokehjs/src/lib/embed/notebook.ts
sphinx/source/docs/releases/0.12.9.rst
sphinx/source/docs/user_guide/notebook.rst
```
Just to note, currently naming conventions in the jupyter community are all over the place, with some still using `ipy` prefix, that doesn't seem to be appropriate anymore in my opinion.

@bryevdv, any thoughts?

**Comment by bryevdv** [comment]
Fine w/ me the current name is pretty clunky even if clunky seems to be the standard for jlab things. @canavandl ?

**Comment by philippjfr** [comment]
+1 in general, but I'd also be happy enough if the new Python package containing the ipywidget to be called `jupyter_bokeh` and to keep the repo name as is.

**Comment by bryevdv** [comment]
@philippjfr are there specific reasons you don't want to rename the repo?

**Comment by philippjfr** [comment]
Sorry if I wasn't clear. I'm very much in favor of renaming the repo, but if someone else objects at minimum I'd expect the new Python package to be called jupyter_bokeh since it is not in any way limited to JupyterLab.

**Comment by bryevdv** [comment]
ok, I think we should rename the repo to match.
