### ISSUE TITLE
Document development and deployment

### ISSUE THREAD

**Issue by mattpap** [bokeh/jupyter_bokeh#75]
Development is partially explained in `README.md`. Need to document uploads to npm, anaconda cloud and pypi.

**Comment by bryevdv** [comment]
FYI need t upload to pypi w/ twine:
```
twine upload -u __token__ -p <token> <file>
```
Also we need to make a new token scoped to just this project and put it in 1pass

**Comment by bryevdv** [comment]
Need to document: 

* conventions for dev versions
* `python setup.py sdist bdist_wheel` to build
* `npm publish` to publish to NPM
* set `PYPI_TOKEN` and `twine upload -u __token__ -p $PYPI_TOKEN dist/jupyter_bokeh-*` to publish to PyPI
* instructions for conda package (tbd)

It's possible the `deploy.sh` script can be used (or lightly fixed up) to do all this

cc  @philippjfr
