### ISSUE TITLE
Extension doesn't install on jupyterlab 2.0.0

### ISSUE THREAD

**Issue by codypiersall** [bokeh/jupyter_bokeh#88]
Jupyter Lab recently bumped its major version, and now this extension won't install, failing with the following message:

```
Building jupyterlab assets (build:prod:minimize)
An error occured.
ValueError: This extension does not yet support the current version of JupyterLab.
```

I guess it is because of [these lines in `package.json`](https://github.com/bokeh/jupyter_bokeh/blob/1455c5599afc7e6c2a6630be39497f6a90c59e88/package.json#L29-L40):

```json
  "dependencies": {
    "@jupyterlab/application": "^1.1.3",
    "@jupyterlab/apputils": "^1.1.3",
    "@jupyterlab/docregistry": "^1.1.3",
    "@jupyterlab/notebook": "^1.1.3",
    "@jupyterlab/rendermime-interfaces": "^1.4.0",
    "@jupyterlab/services": "^4.1.1",
    "@jupyter-widgets/base": "^2.0.1",
    "@phosphor/coreutils": "^1.3.1",
    "@phosphor/disposable": "^1.3.1",
    "@phosphor/widgets": "^1.9.3"
  },
```

I'm not sure if the extension *really* isn't compatible, or if the dependency was pinned just to be cautious.

**Comment by mattpap** [comment]
There's a [migration guide](https://jupyterlab.readthedocs.io/en/stable/developer/extension_migration.html#extension-migration). Looks like it's only name changing due to recent "events".

**Comment by mattpap** [comment]
> I'm not sure if the extension really isn't compatible, or if the dependency was pinned just to be cautious.

These dependencies aren't pinned. Pinning is setting a version to a specific number, for any reasons. Here we use semver ranges, which correctly identify what versions of jlab this extension supports.

**Comment by codypiersall** [comment]
@mattpap, My mistake on using the wrong terminology.  Thanks for the feedback.  I didn't realize there was a different term for pinning an exact version and specifying a range.

For anyone else interested, the name change was due to the author of PhosphorJS archiving the project, so the JupyterLab team is maintaining a fork under a different name.

**Comment by kennorsdb** [comment]
I'm also interested on this issue. Thanks for all your work!!

**Comment by bryevdv** [comment]
We will have a new 2.x release out in the next few weeks (we have to get through the Bokeh 2.0 release first)
