### ISSUE TITLE
Some improvement possible in CI script

### ISSUE THREAD

**Issue by consideRatio** [bokeh/jupyter_bokeh#91]
These are the current CI steps run as declared in .travis.yml file.

```
script:
- npm install
- npm run build
- PARSER_NO_WATCH=true npm run lint
- jupyter labextension install .
- jupyter lab clean
- python -m jupyterlab.browser_check
```

I don't know the current state of jupyterlab things well enough, but I'm quite confident we are doing some steps not needed.

1. Usage of `link` is meant to enable us to make changes easier, but this will only run once in a ephemeral environment anyhow. And, whenever we run `jupyter labextension link` or `jupyter labextension install` it will start a slow build process of all javascript to become the bundle passed to the browser. Let's remove one of these.
2. We don't use `--minimize=False` which defaults to True on the install / link step. This takes some extra time I think.
3. We don't use the new `jlpm` stuff I've seen to replace some jupyter commands. Both seem to work, but we may want to transition to what is the new standard.

**Comment by bryevdv** [comment]
TravisCI is no longer used.
