### ISSUE TITLE
Plots made with Bokeh do not re-render when refreshing Jupyter notebook tab

### ISSUE THREAD

**Issue by cuspime** [bokeh/jupyter_bokeh#98]
When I refresh the page of my Jupyter notebook, no Bokeh plots are shown.
As suggested [on this thread](https://github.com/bokeh/jupyter_bokeh/issues/49#issuecomment-606174275), I am using

output_notebook(hide_banner=True)

But this does not solve the problem. Is there a way to have the plots to show automatically in its latest state before refreshing, like matplotlib or seaborn do.

Is it possible to show them on GitHub or nbviewer?

**Comment by bryevdv** [comment]
@cuspime aplogies, I meant on the main repo: https://github.com/bokeh/bokeh

**Comment by bryevdv** [comment]
> Is it possible to show them on GitHub or nbviewer?

AFAIK nbviewer still functions as expected. Please know that it will likely *never* be possible to see live Bokeh plots on GitHub, because GitHub scrubs all JavaScript when it renders notebooks, and Bokeh plots require JavaScript to display. We have no control over this.

**Comment by bryevdv** [comment]
I just checked with `jupyter nbconvert --to html  quickstart.ipynb` and and Bokeh 2.0.1 and i generated rendered notebook HTML with plots included.

**Comment by bryevdv** [comment]
That said, I have not been able to get `nbviewer.org` in particular to refresh new content. Others seem to be having an issue as well, there is an issue here https://github.com/jupyter/nbviewer/issues/914
